version: "3.7"
services:
  web-server:
    image: popstar13/crudback
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - phpmyadmin
    deploy:
      replicas: 3
    app_network:   # <-- Добавляем сеть
    и
      
  db:
    image: popstar13/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'lena'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'secret'
    ports:
      - "5000:80"

networks:
  app_default:      # <-- Определяем сеть
    driver: overlay
    attachable: true  # <-- КЛЮЧЕВОЕ! Позволяет подключать внешние сервисы (canary)
    
volumes:
  mysql-data:
